branches:
  only:
  - master
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ResponseMasking.AspNetCore.Filter.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./src/ResponseMasking.AspNetCore.Filter.csproj
